#/bin/bash

# This script generates a video from a series of images using ffmpeg, the frames are
# generated by "make_frames.py" 

# The script takes the following arguments:
# 1. The path to the input file

output_file="output.mp4"
input_file=$1

# Check if the input file exists
if [ ! -f $input_file ]; then
    echo "The input file does not exist"
    exit 1
fi

echo "Generating frames..."

python make_frames.py --input_file $input_file

echo "Generating video..."

## change to the directory where the frames are stored



ffmpeg -framerate 5 -i frame_%04d.png -c:v libx264 -pix_fmt yuv420p $output_file
